<div class="page-title main-title">
    <h1><span><?php echo $this->__('MY ACCOUNT') ?></span></h1>
    <?php
    $breadcrumbs = $this->getLayout()->getBlock('breadcrumbs');         
    $breadcrumbs->addCrumb('home', array('label'=>Mage::helper('cms')->__('Home'), 'title'=>Mage::helper('cms')->__('Home'), 'link'=>Mage::getBaseUrl()));     
    $breadcrumbs->addCrumb('my_account', array('label'=>'My Account', 'title'=>'My Account'));         
    echo $this->getLayout()->getBlock('breadcrumbs')->toHtml();
    ?>	    
</div>
<div class="col2-set login-form">
    <div class="col-1 registered-users">
        <div class="content">
            <h2><?php echo $this->__('Returning Customers') ?></h2>
            <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="login-form">
                <ul class="form-list">
                    <li>
                        <label for="email" class="required"><?php echo $this->__('Email Address') ?><em>*</em></label>
                        <div class="input-box">
                            <input type="text" name="login[username]" value="<?php echo $this->htmlEscape($this->getUsername()) ?>" id="email" class="input-text required-entry validate-email" title="<?php echo $this->__('Email Address') ?>" />
                        </div>
                    </li>
                    <li>
                        <label for="pass" class="required"><?php echo $this->__('Password') ?><em>*</em></label>
                        <div class="input-box">
                            <input type="password" name="login[password]" class="input-text required-entry validate-password" id="pass" title="<?php echo $this->__('Password') ?>" />
                        </div>
                    </li>
                </ul><br>
                <div class="buttons-set">
                    <a href="<?php echo $this->getForgotPasswordUrl() ?>"><?php echo $this->__('I forgot my password') ?></a>
                    <?php echo $this->getChildHtml('form.additional.info'); ?>
                    <?php echo $this->getChildHtml('persistent.remember.me'); ?>
                    <?php echo $this->getChildHtml('persistent.remember.me.tooltip'); ?>
                    <div class="rememberme"><br>
                        <label for="check-remember"><input id="check-remember" type="checkbox" />
                        Remember me</label>
                    </div><br>
                    <button type="submit" class="fluid ui orange button" title="<?php echo $this->__('Sign in') ?>" name="send" id="send2"><?php echo $this->__('Sign in') ?></button>           <br>
<br>
         
                </div>                
            </form>
            <script type="text/javascript">
            //<![CDATA[
                var dataForm = new VarienForm('login-form', true);
            //]]>
            </script>
        </div>
    </div>
    <div class="col-2 new-users">
        <?php echo $this->getChildHtml('customer_form_register2'); ?>        
    </div>
</div>