<div class="page-title main-title">
    <h1><span><?php echo $this->__('MY ACCOUNT') ?></span></h1>
    <?php
    $breadcrumbs = $this->getLayout()->getBlock('breadcrumbs');         
    $breadcrumbs->addCrumb('home', array('label'=>Mage::helper('cms')->__('Home'), 'title'=>Mage::helper('cms')->__('Home'), 'link'=>Mage::getBaseUrl()));     
    $breadcrumbs->addCrumb('my_account', array('label'=>'My Account', 'title'=>'My Account'));         
    echo $this->getLayout()->getBlock('breadcrumbs')->toHtml();
    ?>	    
</div>
<div class="col2-set login-form">
    <div class="col-1 registered-users">
        <div class="content">
            <h2><?php echo $this->__('New Customers') ?></h2>
            <h3><?php echo $this->__('CREATE AN ACCOUNT TO TAKE ADVANTAGE OF THESE GREAT BENEFITS:') ?></h3>
            <ul class="new-users-list">
                <li><?php echo $this->__('Check your order status and order history') ?></li>
                <li><?php echo $this->__('Create and share a wish list') ?></li>
                <li><?php echo $this->__('Share your thoughts - Write a product review') ?></li>
                <li><?php echo $this->__('Set your sport preferences and receive  specialized product recommendations') ?></li>
                <li><?php echo $this->__('Learn about innovative technologies used in product design and construction') ?></li>
                <li><?php echo $this->__('Register for an event and put your training (and gear) to the test') ?></li>
            </ul><br><br>
            <?php echo $this->getChildHtml('form_fields_before')?>
            <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
            <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="form-validate">
                <input type="hidden" name="success_url" value="<?php echo $this->getSuccessUrl() ?>" />
                <input type="hidden" name="error_url" value="<?php echo $this->getErrorUrl() ?>" />
                <?php if($this->getShowAddressFields()): ?>
                    <input type="hidden" name="create_address" value="1" />
                    <input type="hidden" name="default_billing" value="1" />
                    <input type="hidden" name="default_shipping" value="1" />
                <?php endif;?>        
                <ul class="form-list">
                    <li>    
                        <?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getFormData())->setForceUseCustomerAttributes(true)->toHtml() ?>
                    </li>    
                    <li>
                        <label for="email_address" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
                        <div class="input-box">
                            <input type="text" name="email" id="email_address" value="<?php echo $this->escapeHtml($this->getFormData()->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" class="input-text validate-email required-entry" />
                        </div>
                    </li>
                    <?php $_dob = $this->getLayout()->createBlock('customer/widget_dob') ?>
                    <?php if ($_dob->isEnabled()): ?>
                        <li><?php echo $_dob->setDate($this->getFormData()->getDob())->toHtml() ?></li>
                    <?php endif ?>
                    <?php $_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat') ?>
                    <?php if ($_taxvat->isEnabled()): ?>
                        <li><?php echo $_taxvat->setTaxvat($this->getFormData()->getTaxvat())->toHtml() ?></li>
                    <?php endif ?>
                    <?php $_gender = $this->getLayout()->createBlock('customer/widget_gender') ?>
                    <?php if ($_gender->isEnabled()): ?>
                        <li><?php echo $_gender->setGender($this->getFormData()->getGender())->toHtml() ?></li>
                    <?php endif ?>
                    <?php if($this->getShowAddressFields()): ?>               
                        <li class="fields">
                            <div class="field">
                                <label for="company"><?php echo $this->__('Company') ?></label>
                                <div class="input-box">
                                    <input type="text" name="company" id="company" value="<?php echo $this->escapeHtml($this->getFormData()->getCompany()) ?>" title="<?php echo $this->__('Company') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('company') ?>" />
                                </div>
                            </div>
                            <div class="field">
                                <label for="telephone" class="required"><em>*</em><?php echo $this->__('Telephone') ?></label>
                                <div class="input-box">
                                    <input type="text" name="telephone" id="telephone" value="<?php echo $this->escapeHtml($this->getFormData()->getTelephone()) ?>" title="<?php echo $this->__('Telephone') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('telephone') ?>" />
                                </div>
                            </div>
                        </li>
                        <?php $_streetValidationClass = $this->helper('customer/address')->getAttributeValidationClass('street'); ?>
                            <li class="wide">
                                <label for="street_1" class="required"><em>*</em><?php echo $this->__('Street Address') ?></label>
                                <div class="input-box">
                                    <input type="text" name="street[]" value="<?php echo $this->escapeHtml($this->getFormData()->getStreet(1)) ?>" title="<?php echo $this->__('Street Address') ?>" id="street_1" class="input-text <?php echo $_streetValidationClass ?>" />
                                </div>
                            </li>
                        <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
                        <?php for ($_i = 2, $_n = $this->helper('customer/address')->getStreetLines(); $_i <= $_n; $_i++): ?>
                            <li class="wide">
                                <div class="input-box">
                                    <input type="text" name="street[]" value="<?php echo $this->escapeHtml($this->getFormData()->getStreet($_i)) ?>" title="<?php echo $this->__('Street Address %s', $_i) ?>" id="street_<?php echo $_i ?>" class="input-text <?php echo $_streetValidationClass ?>" />
                                </div>
                            </li>
                        <?php endfor; ?>
                            <li class="fields">
                                <div class="field">
                                    <label for="city" class="required"><em>*</em><?php echo $this->__('City') ?></label>
                                    <div class="input-box">
                                        <input type="text" name="city" value="<?php echo $this->escapeHtml($this->getFormData()->getCity()) ?>" title="<?php echo $this->__('City') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('city') ?>" id="city" />
                                    </div>
                                </div>
                                <div class="field">
                                    <label for="region_id" class="required"><em>*</em><?php echo $this->__('State/Province') ?></label>
                                    <div class="input-box">
                                        <select id="region_id" name="region_id" title="<?php echo $this->__('State/Province') ?>" class="validate-select" style="display:none;">
                                            <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                                        </select>
                                        <script type="text/javascript">
                                        //<![CDATA[
                                            $('region_id').setAttribute('defaultValue', "<?php echo $this->getFormData()->getRegionId() ?>");
                                        //]]>
                                        </script>
                                        <input type="text" id="region" name="region" value="<?php echo $this->escapeHtml($this->getRegion()) ?>" title="<?php echo $this->__('State/Province') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('region') ?>" style="display:none;" />
                                    </div>
                                </div>
                            </li>
                            <li class="fields">
                                <div class="field">
                                    <label for="zip" class="required"><em>*</em><?php echo $this->__('Zip/Postal Code') ?></label>
                                    <div class="input-box">
                                        <input type="text" name="postcode" value="<?php echo $this->escapeHtml($this->getFormData()->getPostcode()) ?>" title="<?php echo $this->__('Zip/Postal Code') ?>" id="zip" class="input-text validate-zip-international <?php echo $this->helper('customer/address')->getAttributeValidationClass('postcode') ?>" />
                                    </div>
                                </div>
                                <div class="field">
                                    <label for="country" class="required"><em>*</em><?php echo $this->__('Country') ?></label>
                                    <div class="input-box">
                                        <?php echo $this->getCountryHtmlSelect() ?>
                                    </div>
                                </div>
                            </li>                
                    <?php endif; ?>
                    <li>
                        <label for="password" class="required"><em>*</em><?php echo $this->__('Password') ?></label>
                        <div class="input-box">
                            <input type="password" name="password" id="password" title="<?php echo $this->__('Password') ?>" class="input-text required-entry validate-password" />
                        </div>
                    </li>
                    <li>
                        <label for="confirmation" class="required"><em>*</em><?php echo $this->__('Confirm Password') ?></label>
                        <div class="input-box">
                            <input type="password" name="confirmation" title="<?php echo $this->__('Confirm Password') ?>" id="confirmation" class="input-text required-entry validate-cpassword" />
                        </div>
                    </li>
                    <?php echo $this->getChildHtml('form.additional.info'); ?>            
                </ul>
                <?php if ($this->isNewsletterEnabled()): ?><br>
                    <div class="sendme">               
                        <input type="checkbox" name="is_subscribed" title="<?php echo $this->__('Sign Up for Newsletter') ?>" value="1" id="is_subscribed"<?php if($this->getFormData()->getIsSubscribed()): ?> checked="checked"<?php endif; ?> class="checkbox" />               
                        <label for="is_subscribed"><?php echo $this->__('Please send me emails with exclusive gear offers and AMK updates and promotions.') ?></label>
                        <?php /* Extensions placeholder */ ?>
                        <?php echo $this->getChildHtml('customer.form.register.newsletter')?>
                    </div>
                <?php endif ?>        <br>
                <div class="buttons-set">
                    <button type="submit" title="<?php echo $this->__('Create Account') ?>" class="fluid ui orange button"><?php echo $this->__('Create Account') ?></button>            
                </div>
            </form>
            <script type="text/javascript">
            //<![CDATA[
                var dataForm = new VarienForm('form-validate', true);
                <?php if($this->getShowAddressFields()): ?>
                new RegionUpdater('country', 'region', 'region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'zip');
                <?php endif; ?>
            //]]>
            </script>   
        </div>
    </div>
</div>