<?php
/**
 * Outsource Online Captcha Extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   Outsource Online
 * @package    OutsourceOnline_Captcha
 * @author     Sreekanth Dayanand
 * @copyright  Copyright (c) 2010 Outsource Online. (http://www.outsource-online.net)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/**
 * Send to friend form
 *
 * @see Mage_Sendfriend_Block_Index
 */
?>

<script type="text/javascript">
//<![CDATA[
    i=0;
    var recipCount  = 1;
    var maxRecip    = <?php echo $this->getMaxRecipients() ?>;
    function remove_recipient(i){
        $('recipients_name'+i).up(2).remove();
        recipCount--;
        if(recipCount<maxRecip && maxRecip != 0) {
            $('add_recipient_button').show();
            $('max_recipient_message').hide();
        }
        return false;
    }

    function add_recipient(){
        ul = $('recipients_options');
        var li_mail = Element.extend(document.createElement("LI"));
        li_mail.addClassName('addElement');
        li_mail.innerHTML = '<div align="right"><a href="delete_email" onclick="remove_recipient('+i+');return false"><img src="<?php echo $this->getSkinUrl('images/list_remove_btn.gif') ?>" alt="<?php echo $this->__('Remove Email') ?>"/><\/a><\/div>'
        li_mail.innerHTML += '<div class="left"><label for="recipients_name"><?php echo $this->__('Name:') ?> <span class="required">*<\/span><\/label><br /><div style="width:250px"><input name="recipients[name][]" type="text" class="input-text required-entry" id="recipients_name'+i+'" style="width:250px;" /><\/div><br /><br /><\/div>';
        li_mail.innerHTML += '<div class="right"><label for="recipients_email"><?php echo $this->__('Email Address:') ?><span class="required">*<\/span><\/label><br /><div style="width:250px"><input name="recipients[email][]" value="" title="<?php echo $this->__('Email Address') ?>" id="recipients_email'+i+'" type="text" class="input-text required-entry validate-email" style="width:250px;" /><\/div><\/div>';
        i++;
        recipCount++;
        if(recipCount>=maxRecip && maxRecip != 0) {
            $('add_recipient_button').hide();
            $('max_recipient_message').show();
        }

        ul.appendChild(li_mail);
    }
//]]>
</script>

<div class="send-friend">
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <h1><?php echo $this->__('Email to a Friend') ?></h1>
    <form action="<?php echo $this->getUrl('*/*/sendmail', array('id'=>$this->getProductId(), 'cat_id'=>$this->getCategoryId())) ?>" method="post" id="product_sendtofriend_form" onSubmit="return checkOSOLCaptcha(productSendtofriendForm);">
        <input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>">
        <div class="edit-account-info">
			<div class="edit-account-info-content">
                <h2><?php echo $this->__('Sender:') ?></h2>
                <ul class="form-list-edit" id="sender_options">
                    <li>
                        <div class="field">
                            <label for="sender_name"><em>*</em><?php echo $this->__('Name:') ?></label>
                            <div class="input-box">
                                <input name="sender[name]" value="<?php echo $this->htmlEscape($this->getUserName()) ?>" title="<?php echo $this->__('Name') ?>" id="sender_name" type="text" class="input-text required-entry" />
                            </div>
                        </div>
                    </li>
                    <li>
                        <div class="field">
                           <label for="sender_email" class="required"><em>*</em><?php echo $this->__('Email:') ?></label>
                           <div class="input-box">
                               <input name="sender[email]" value="<?php echo $this->htmlEscape($this->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" id="sender_email" type="text" class="input-text required-entry validate-email" />
                           </div>
                        </div>
                    </li>
                    <li class="wide">
                        <label for="sender_message" class="required"><em>*</em><?php echo $this->__('Message:') ?></label>
                        <div class="input-box">
                            <textarea name="sender[message]" class="input-text required-entry" id="sender_message" cols="3" rows="3"><?php echo $this->htmlEscape($this->getFormData()->getData('sender/message'))?></textarea>
                        </div>
                    </li>
                </ul>
                
                <h2><?php echo $this->__('Recipient:') ?></h2>
                <ul class="form-list-edit" id="recipients_options">
                    <li>
                        <div class="field">
                            <label for="recipients_name" class="required"><em>*</em><?php echo $this->__('Name:') ?></label>
                            <div class="input-box">
                                <input name="recipients[name][]" type="text" class="input-text required-entry" id="recipients_name" />
                            </div>
                        </div>
                    </li>
                    <li>
                        <div class="field">
                            <label for="recipients_email" class="required"><em>*</em><?php echo $this->__('Email Address:') ?></label>
                            <div class="input-box">
                                <input name="recipients[email][]" value="" title="<?php echo $this->__('Email Address') ?>" id="recipients_email" type="text" class="input-text required-entry validate-email" />
                            </div>
                        </div>
                    </li>
                </ul>
                
                <?php  // recaptcha
                    if( !(Mage::getStoreConfig("OutsourceOnline_Captcha/captcha/when_loggedin")  && (Mage::getSingleton('customer/session')->isLoggedIn())) )
                    {
                        if (Mage::getStoreConfig("OutsourceOnline_Captcha/captcha/sendfriend"))
                           echo $this->getChildHtml('captcha_ajax_part');
                    }
                ?>
                
                <div class="buttons-set">
                    <p class="back-link"><a href="#" onclick="history.back(); return false;"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
                    <button type="submit" class="button<?php if (!$this->canSend()):?> disabled<?php endif ?>"<?php if (!$this->canSend()):?> disabled="disabled"<?php endif ?>><?php echo $this->__('Send Email') ?></button>
                    <div id="max_recipient_message" style="display:none;">
                        <?php if ($this->getMaxRecipients()): ?>
                          <p class="limit"><?php echo $this->__('Maximum %d email addresses allowed.', $this->getMaxRecipients()) ?></p>
                        <?php endif; ?>
                    </div>
                    <?php if (1 < $this->getMaxRecipients()): ?>
                        <p id="add_recipient_button">
                            <button type="button" onclick="add_recipient();" class="button"><?php echo $this->__('Add Recipient') ?></button>
                        </p>
                    <?php endif; ?>
                </div>
            </div>
            
            <div class="sidebar">
                <div class="sub-side-box-first">
                    <?php echo$this->getLayout()->createBlock('cms/block')->setBlockId('perfect-vacuum')->toHtml() ?>
                </div>
                <div class="sub-side-box worry-free">
                <?php echo$this->getLayout()->createBlock('cms/block')->setBlockId('worry-free')->toHtml() ?>
                </div>
                <div class="sub-side-box overnight-delivery">
                <?php echo$this->getLayout()->createBlock('cms/block')->setBlockId('overnight-delivery')->toHtml() ?>
                </div>
                <div class="sub-side-box bbb">
                <?php echo$this->getLayout()->createBlock('cms/block')->setBlockId('bbb-rating')->toHtml() ?>
                </div>
                <div class="sub-side-box fgs">
                    <?php echo$this->getLayout()->createBlock('cms/block')->setBlockId('free-ground-shipping')->toHtml() ?>
                </div>
            </div>
        </div>
    </form>
</div>

<script type="text/javascript">
    var productSendtofriendForm = new VarienForm('product_sendtofriend_form');
    productSendtofriendForm.submit = function() {
        if(this.validator.validate()) {
            this.form.submit();
        }
    }.bind(productSendtofriendForm);
</script>
